# Generated by Django 2.0.2 on 2018-02-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(),
        ),
    ]
