# Generated by Django 2.0.2 on 2018-02-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileID',
            fields=[
                ('profID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='profID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contents.profileID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contents.profileID'),
            preserve_default=False,
        ),
    ]
