# Generated by Django 2.0.2 on 2018-02-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20180208_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='profID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='model_pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profID',
        ),
        migrations.DeleteModel(
            name='profileID',
        ),
    ]
