# Generated by Django 2.0.2 on 2018-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eye',
            field=models.ImageField(default='pic_folder/None/no-eyemg.jpg', upload_to='pic_folder/eyes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/faces/'),
        ),
    ]
